version: "3.8"
services:
  app-dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
