version: "3.8"
services:
  app-dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4000:3000
    environment:
      - ENV=development
    command: "npm run start"
