version: "3.8"
services:
  swapi-app:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4000:4000
    env_file:
      - ./.docker/dev/.env.prod
    command: "npm run start"
